# Generated by Django 3.2.4 on 2021-06-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('categoria', models.CharField(choices=[('Electrodomesticos', 'Electrodomesticos'), ('Electrónica', 'Electrónica'), ('Deportes', 'Deportes'), ('Bebés', 'Bebés'), ('Hogar', 'Hogar')], max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
