# Generated by Django 3.2.4 on 2021-07-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_categorias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorias',
            old_name='Descripcion',
            new_name='descripcion',
        ),
    ]
